// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6RtfYZSntuaE66O-vyY81KHXRWnGIFo4',
    appId: '1:417222072277:web:2a270a69b8c49058504f5c',
    messagingSenderId: '417222072277',
    projectId: 'mturobotcontroller-1d7d9',
    authDomain: 'mturobotcontroller-1d7d9.firebaseapp.com',
    storageBucket: 'mturobotcontroller-1d7d9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClUMogNYhLMvvDYAnqPw0_qgCOiPK2TQk',
    appId: '1:417222072277:android:4cd0a4335fe2313e504f5c',
    messagingSenderId: '417222072277',
    projectId: 'mturobotcontroller-1d7d9',
    storageBucket: 'mturobotcontroller-1d7d9.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6RtfYZSntuaE66O-vyY81KHXRWnGIFo4',
    appId: '1:417222072277:web:b93dc972b94e6fdb504f5c',
    messagingSenderId: '417222072277',
    projectId: 'mturobotcontroller-1d7d9',
    authDomain: 'mturobotcontroller-1d7d9.firebaseapp.com',
    storageBucket: 'mturobotcontroller-1d7d9.firebasestorage.app',
  );
}
